name: rust_ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - name: Build
       uses: actions-rs/toolchain@v1
       with:
         toolchain: nightly
         run: cargo build --verbose
     - name: Run tests
       uses: actions-rs/toolchain@v1
       with:
         toolchain: nightly
         run: cargo test --verbose