name: rust_ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      name: Build
      with:
        toolchain: nightly
      run: cargo build --verbose
    - uses: actions-rs/toolchain@v1
      name: Run tests
      with:
        toolchain: nightly
      run: cargo test --verbose